project:
  type: website
  output-dir: .

website:
  title: "Data Science Training Program"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Session 1"
        href: ./Notes_session1.qmd
      - text: "Session 2"
        href: ./Notes_session2.qmd
      # - text: "Assignments"
      #   href: assignments.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true

editor: visual

