project:
  type: website
  output-dir: .

website:
  title: "WOAH - DATA SCIENCE TRAINING PROGRAM"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Rstudio"
        href: Notes_session1.qmd
      - text: "Syntax & Vocabulary I"
        href: Notes_session2.qmd
      - text: "Syntax & Vocabulary II"
        href: Notes_session3.qmd
      - text: "Quarto"
        href: quarto.qmd
      - text: "Git"
        href: git.qmd
      - text: "AI"
        href: AI.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true



