project:
  type: website

website:
  title: "My Course Materials"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: ./Training_Session_1/Notes_session1.qmd
      # - text: "Assignments"
      #   href: assignments.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

