project:
  type: website
  output-dir: .

website:
  title: "DATA SCIENCE TRAINING PROGRAM"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Rstudio"
        href: Notes_session1.qmd
      - text: "Data wrangling & plotting"
      #   href: Notes_session2.qmd
      # - text: "Data wrangling & plotting II"
        href: Notes_session3.qmd
      - text: "Creating content with Quarto"
        href: quarto.qmd
      - text: "Statistical modelling"
        href: stat.qmd
      - text: "Georeferenced data"
        href: geo.qmd
      - text: "Collaborating with Git"
        href: git.qmd
      - text: "Leveraging AI"
        href: AI.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true
 


