project:
  type: website
  output-dir: .

website:
  title: "WOAH - DATA SCIENCE TRAINING PROGRAM"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Rstudio"
        href: Notes_session1.qmd
      - text: "Data wrangling & plotting I"
        href: Notes_session2.qmd
      - text: "Data wrangling & plotting II"
        href: Notes_session3.qmd
      - text: "Quarto"
        href: quarto.qmd
      - text: "Georeferenced data"
        href: geo.qmd
      - text: "Git"
        href: git.qmd
      - text: "AI"
        href: AI.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true
 


